general_cat_list = ['Inquiry',
 'Question',
 'Query',
 'Request',
 'Information',
 'Assistance',
 'Help',
 'Clarification',
 'Guidance',
 'Advice',
 'Introduction',
 'Introduction Email',
 'Curiosity',
 'General Query',
 'General Request',
 'General Information',
 'Explanation',
 'Explore',
 'Explore Options',
 'Learn',
 'Understanding',
 'Inquiry Email',
 'Need Information',
 'Need Assistance',
 'Wondering',
 'General Question',
 'General Assistance',
 'General Help',
 'Uncertainty',
 'General Communication',
 'Seeking Information',
 'Inquiry About',
 'General Curiosity',
 'Interested In',
 'General Inquiry Email',
 'Request for Information',
 'Inquiry Regarding',
 'General Guidance',
 'Inquiry for Assistance',
 'General Advice',
 'General Clarification',
 'General Introduction',
 'Explore Opportunities',
 'Learn More',
 'Want to Know',
 'Want Information',
 'General Correspondence',
 'General Interaction',
 'General Inquiry Regarding',
 'General Inquiry About',
 'Request for Assistance',
 'Seeking Guidance',
 'Seeking Advice',
 'General Inquiry Regarding [Specific Topic]',
 'General Inquiry About [Specific Subject]',
 'Need Help',
 'General Inquiry Regarding Services',
 'General Inquiry About Products',
 'General Inquiry About [Company Name]',
 'General Inquiry About [Product/Service Name]',
 'General Inquiry About [Topic/Area of Interest]',
 'General Inquiry About [Event/Program]',
 'General Inquiry Regarding [Procedure/Process]',
 'Want to Learn More About',
 'Inquiring About',
 'General Inquiry About [Policy/Rule]',
 'General Inquiry Regarding [Department/Team]',
 'Request for [Information/Assistance]',
 'General Inquiry Related to [Specific Context]',
 'General Inquiry About [Offer/Opportunity]',
 'Inquiring Regarding [Topic/Subject]',
 'General Inquiry Concerning',
 'General Inquiry Related to [Product/Service]',
 'General Inquiry Regarding [Issue/Concern]',
 'Seeking Information About',
 'General Inquiry About [Event/Activity]',
 'Request for Help',
 'General Inquiry Regarding [Project/Initiative]',
 'General Inquiry About [Training/Workshop]',
 'General Inquiry for [Specific Purpose]',
 'General Inquiry for [Assistance/Support]',
 'General Inquiry Regarding [Date/Time]',
 'General Inquiry Regarding [Location/Venue]',
 'General Inquiry Regarding [Availability]',
 'Request for Guidance',
 'General Inquiry for [Specific Information]',
 'General Inquiry for [General Purpose]',
 'General Inquiry About [Application/Software]',
 'General Inquiry Regarding [Registration/Signup]',
 'General Inquiry Regarding [Pricing/Cost]',
 'General Inquiry About [Membership/Subscription]',
 'General Inquiry About [Policy/Procedure]',
 'General Inquiry Regarding [Feedback/Suggestions]',
 'General Inquiry About [Billing/Invoice]',
 'General Inquiry Concerning [Product/Service]',
 'General Inquiry Related to [Company/Brand]',
 'General Inquiry for [Event/Function]',
 'General Inquiry Regarding [Product/Service] Features',
 'General Inquiry Regarding [Delivery/Shipping]',
 'Request for Information About',
 'General Inquiry for [Training/Certification]',
 'General Inquiry for [Collaboration/Partnership]',
 'Seeking Information Regarding',
 'General Inquiry Regarding [Returns/Refunds]',
 'General Inquiry About [Contract/Agreement]',
 'General Inquiry About [Job/Position]',
 'General Inquiry Regarding [Qualifications/Requirements]',
 'General Inquiry Concerning [Event/Conference]',
 'General Inquiry for [Product/Service] Demo',
 'General Inquiry Regarding [Terms/Conditions]',
 'General Inquiry About [Customer Support/Service]',
 'General Inquiry About [Website/Platform]',
 'General Inquiry for [Discounts/Promotions]',
 'General Inquiry About [Privacy/Security]',
 'General Inquiry Concerning [Complaint/Issue]',
 'General Inquiry Regarding [Technical Support]',
 'General Inquiry Regarding [Training/Workshop] Schedule',
 'General Inquiry for [Meeting/Appointment]',
 'General Inquiry for [Project/Assignment]',
 'General Inquiry for [Collaboration/Networking]',
 'General Inquiry About [New Features/Updates]',
 'General Inquiry About [Sales/Revenue]',
 'General Inquiry Concerning [Product/Service] Quality',
 'General Inquiry Regarding [Product/Service] Availability',
 'General Inquiry About [Product/Service] Pricing',
 'General Inquiry for [Feedback/Opinions]',
 'General Inquiry for [Product/Service] Comparison',
 'General Inquiry for [Product/Service] Specifications',
 'General Inquiry Concerning [Billing/Payment]',
 'General Inquiry for [Product/Service] Trial',
 'General Inquiry Regarding [Event/Program] Details',
 'General Inquiry for [Membership/Subscription] Renewal',
 'General Inquiry Regarding [Technical/Functionalities]',
 'General Inquiry for [Collaboration/Partnership] Opportunities',
 'General Inquiry for [Job/Internship] Openings',
 'General Inquiry for [Customer Support/Service] Hours',
 'General Inquiry for [Customer Support/Service] Contact',
 'General Inquiry for [Customer Support/Service] Escalation',
 'General Inquiry About [Company/Brand] Background',
 'General Inquiry About [Company/Brand] Values',
 'General Inquiry About [Company/Brand] Culture',
 'General Inquiry for [Event/Conference] Registration',
 'General Inquiry for [Event/Conference] Speakers',
 'General Inquiry for [Event/Conference] Sponsorship',
 'General Inquiry for [Event/Conference] Agenda',
 'General Inquiry About [Product/Service] Upgrades',
 'General Inquiry Regarding [Product/Service] Compatibility',
 'General Inquiry Regarding [Product/Service] Warranty',
 'General Inquiry for [Training/Workshop] Certification',
 'General Inquiry for [Training/Workshop] Materials',
 'General Inquiry for [Training/Workshop] Trainers',
 'General Inquiry for [Training/Workshop] Registration',
 'General Inquiry for [Collaboration/Partnership] Benefits',
 'General Inquiry for [Collaboration/Partnership] Agreements',
 'General Inquiry for [Collaboration/Partnership] Process',
 'General Inquiry for [Collaboration/Partnership] Terms',
 'General Inquiry for [Job/Position] Responsibilities',
 'General Inquiry for [Job/Position] Requirements',
 'General Inquiry for [Job/Internship] Application',
 'General Inquiry for [Job/Internship] Interview',
 'General Inquiry for [Job/Internship] Benefits',
 'General Inquiry for [Job/Internship] Opportunities',
 'General Inquiry for [Qualifications/Requirements] Clarification',
 'General Inquiry for [Qualifications/Requirements] Evaluation',
 'General Inquiry for [Qualifications/Requirements] Matching',
 'General Inquiry for [Event/Function] Participation',
 'General Inquiry for [Event/Function] Registration',
 'General Inquiry for [Event/Function] Attendance',
 'General Inquiry for [Event/Function] Schedule',
 'General Inquiry for [Event/Function] Venue',
 'General Inquiry for [Event/Function] Accommodations',
 'General Inquiry for [Event/Function] Logistics',
 'General Inquiry for [Product/Service] Purchase',
 'General Inquiry Regarding [Product/Service] Installation',
 'General Inquiry Regarding [Product/Service] Maintenance',
 'General Inquiry Regarding [Product/Service] Support',
 'General Inquiry for [Product/Service] Customization',
 'General Inquiry Regarding [Product/Service] Updates',
 'General Inquiry Concerning [Product/Service] Specifications',
 'General Inquiry for [Product/Service] Demos',
 'General Inquiry for [Product/Service] Features',
 'General Inquiry Regarding [Product/Service] Benefits',
 'General Inquiry for [Product/Service] Trials',
 'General Inquiry for [Product/Service] Comparisons',
 'General Inquiry for [Product/Service] Reviews',
 'General Inquiry for [Product/Service] Ratings',
 'General Inquiry Regarding [Product/Service] Durability',
 'General Inquiry Regarding [Product/Service] Efficiency',
 'General Inquiry for [Product/Service] Satisfaction',
 'General Inquiry for [Product/Service] Feedback',
 'General Inquiry Regarding [Product/Service] Complaints',
 'General Inquiry for [Product/Service] Returns',
 'General Inquiry for [Product/Service] Exchanges',
 'General Inquiry for [Product/Service] Upgrades',
 'General Inquiry for [Product/Service] Availability',
 'General Inquiry Regarding [Product/Service] Pricing',
 'General Inquiry for [Product/Service] Discounts',
 'General Inquiry for [Product/Service] Promotions',
 'General Inquiry for [Product/Service] Ordering']


Technical_cat_list = ['Technical Support',
 'Issue',
 'Problem',
 'Error',
 'Bug',
 'Glitch',
 'Troubleshoot',
 'Debug',
 'Fix',
 'Resolve',
 'Technical Difficulty',
 'System',
 'Software',
 'Hardware',
 'Configuration',
 'Installation',
 'Compatibility',
 'Update',
 'Upgrade',
 'Patch',
 'Crash',
 'Freeze',
 'Lag',
 'Performance',
 'Connectivity',
 'Network',
 'Server',
 'Database',
 'Firewall',
 'Security',
 'Authentication',
 'Authorization',
 'Permissions',
 'API',
 'Integration',
 'Deployment',
 'Automation',
 'Scripting',
 'Code',
 'Programming',
 'Development',
 'Framework',
 'Library',
 'SDK',
 'API Key',
 'Endpoint',
 'Logging',
 'Monitoring',
 'Analytics',
 'Metrics',
 'Logging',
 'Debugging',
 'Patching',
 'Version Control',
 'Git',
 'Repository',
 'Branch',
 'Commit',
 'Merge',
 'Pull Request',
 'Continuous Integration',
 'Continuous Deployment',
 'CI/CD',
 'DevOps',
 'Containerization',
 'Docker',
 'Kubernetes',
 'Virtualization',
 'Hypervisor',
 'Cloud',
 'AWS',
 'Azure',
 'Google Cloud',
 'Infrastructure',
 'Architecture',
 'Framework',
 'Framework Issue',
 'Dependency',
 'Package',
 'Library Issue',
 'Component',
 'Module',
 'Plugin',
 'Theme',
 'UI/UX',
 'Design',
 'Layout',
 'Responsiveness',
 'Cross-Browser Compatibility',
 'Mobile Compatibility',
 'Browser Issue',
 'Rendering',
 'CSS',
 'HTML',
 'JavaScript',
 'Frontend',
 'Backend',
 'API Issue',
 'Database Query',
 'SQL',
 'NoSQL',
 'Database Performance',
 'Data Integrity',
 'Data Recovery',
 'Backup',
 'Restore',
 'Data Migration',
 'Data Import/Export',
 'Database Schema',
 'Network Issue',
 'Connectivity Issue',
 'Latency',
 'Bandwidth',
 'Firewall Configuration',
 'Security Patch',
 'SSL/TLS',
 'Certificate',
 'Authentication Issue',
 'Authorization Issue',
 'Access Control',
 'User Role',
 'Login Issue',
 'Password Reset',
 'Account Lockout',
 'Two-Factor Authentication',
 'Email Configuration',
 'SMTP',
 'IMAP',
 'POP3',
 'Mail Server',
 'Email Delivery',
 'Email Bounce',
 'SPAM',
 'Anti-SPAM',
 'DNS',
 'Domain',
 'Subdomain',
 'Hosting',
 'Web Server',
 'Apache',
 'Nginx',
 'IIS',
 'Server Configuration',
 'SSL Certificate Installation',
 'Load Balancing',
 'Content Delivery Network (CDN)',
 'Cache',
 'Performance Optimization',
 'Bottleneck',
 'Memory Leak',
 'Resource Utilization',
 'CPU Usage',
 'Disk Space',
 'File Permissions',
 'File Upload/Download',
 'File Path',
 'File Corruption',
 'Compression',
 'Decompression',
 'API Rate Limiting',
 'API Authentication',
 'API Key Issue',
 'API Versioning',
 'API Documentation',
 'Mobile App Issue',
 'Mobile App Compatibility',
 'Mobile App Performance',
 'Mobile App Update',
 'Mobile App Installation',
 'Mobile App Configuration',
 'Operating System',
 'Windows',
 'macOS',
 'Linux',
 'Android',
 'iOS',
 'Device Compatibility',
 'Driver Issue',
 'Printer Configuration',
 'Scanner Configuration',
 'Peripheral Issue',
 'Hardware Compatibility',
 'Firmware Update',
 'BIOS Update',
 'Device Driver Update',
 'Kernel Panic',
 'Blue Screen of Death (BSOD)',
 'System Crash',
 'Recovery Mode',
 'Safe Mode',
 'Boot Issue',
 'Boot Configuration',
 'BIOS Settings',
 'Disk Management',
 'Disk Partition',
 'Data Loss',
 'System Update',
 'System Restore',
 'System Performance']

feedback_cat_list = ['Feedback',
 'Testimonial',
 'Review',
 'Satisfaction',
 'Experience',
 'Appreciation',
 'Opinion',
 'Comment',
 'Suggestion',
 'Improvement',
 'Praise',
 'Critique',
 'Rating',
 'Recommendation',
 'Kudos',
 'Applause',
 'Acknowledgment',
 'Gratitude',
 'Thanks',
 'Positive',
 'Negative',
 'Constructive',
 'Compliment',
 'Applaud',
 'Pleased',
 'Delighted',
 'Happy',
 'Content',
 'Unhappy',
 'Dissatisfied',
 'Unpleased',
 'Unsatisfied',
 'Like',
 'Dislike',
 'Love',
 'Hate',
 'Impressed',
 'Disappointed',
 'Recommend',
 'Referral',
 'Approval',
 'Disapproval',
 'Quality',
 'Service',
 'Product',
 'Feature',
 'Functionality',
 'Usability',
 'Design',
 'Performance',
 'Reliability',
 'Efficiency',
 'Effectiveness',
 'Timeliness',
 'Responsiveness',
 'Communication',
 'Support',
 'Assistance',
 'Help',
 'Response Time',
 'Resolution',
 'Problem-solving',
 'Communication Skills',
 'Courteous',
 'Professionalism',
 'Knowledgeable',
 'Friendly',
 'Politeness',
 'Availability',
 'Accessibility',
 'Convenience',
 'User-Friendly',
 'Navigation',
 'Website',
 'Mobile App',
 'Interface',
 'Layout',
 'Content',
 'Clarity',
 'Ease of Use',
 'Registration',
 'Onboarding',
 'Payment Process',
 'Checkout',
 'Shipping',
 'Delivery',
 'Packaging',
 'Pricing',
 'Cost',
 'Value for Money',
 'Loyalty',
 'Rewards',
 'Membership',
 'Discounts',
 'Promotions',
 'Deals',
 'Coupons',
 'Subscription',
 'Renewal',
 'Billing',
 'Invoicing',
 'Transparency',
 'Trust',
 'Brand',
 'Reputation',
 'Brand Image',
 'Company',
 'Organization',
 'Mission',
 'Values',
 'Corporate Social Responsibility (CSR)',
 'Environmental Sustainability',
 'Social Impact',
 'Community',
 'Charity',
 'Donation',
 'Initiative',
 'Event',
 'Partnership',
 'Collaboration',
 'Innovation',
 'Creativity',
 'Uniqueness',
 'Originality',
 'Improvement',
 'Development',
 'Progress',
 'Change',
 'Adaptation',
 'Flexibility',
 'Transformation',
 'Evolution',
 'Technology',
 'Digitalization',
 'Automation',
 'AI (Artificial Intelligence)',
 'Machine Learning',
 'User Experience (UX)',
 'Customer Journey',
 'Feedback Loop',
 'Customer Satisfaction Survey',
 'Net Promoter Score (NPS)',
 'Customer Service',
 'Customer Support',
 'Customer Success',
 'Contact Center',
 'Helpdesk',
 'Live Chat',
 'Email Support',
 'Phone Support',
 'Ticket Resolution',
 'Technical Assistance',
 'Knowledge Base',
 'FAQ',
 'Community Forum',
 'Social Media Support',
 'Customer Communication',
 'Customer Interaction',
 'Response',
 'Responsiveness',
 'Listening',
 'Empathy',
 'Understanding',
 'Communication Channel',
 'Omnichannel',
 'Multichannel',
 'Engagement',
 'Personalization',
 'Customization',
 'Individualization',
 'Trustworthiness',
 'Credibility',
 'Authenticity',
 'Honesty',
 'Openness',
 'Transparence',
 'Flexibility',
 'Adaptability',
 'Accountability',
 'Ownership',
 'Initiative',
 'Proactivity',
 'Problem-solving',
 'Innovation',
 'Creativity',
 'Efficiency',
 'Effectiveness',
 'Timeliness',
 'Collaboration',
 'Teamwork',
 'Leadership',
 'Empowerment',
 'Recognition',
 'Appreciation',
 'Motivation',
 'Employee Satisfaction',
 'Workplace Culture',
 'Diversity',
 'Inclusion']

complaints_cat_list = ['Complaint',
 'Dissatisfaction',
 'Unhappy',
 'Displeased',
 'Frustration',
 'Problem',
 'Issue',
 'Error',
 'Unresolved',
 'Defect',
 'Fault',
 'Inconvenience',
 'Trouble',
 'Aggrieved',
 'Upset',
 'Anger',
 'Discontent',
 'Unacceptable',
 'Unresolved Issue',
 'Unmet Expectations',
 'Poor',
 'Subpar',
 'Unsatisfactory',
 'Negligence',
 'Apology',
 'Regrettable',
 'Unsatisfying',
 'Inefficiency',
 'Incompetence',
 'Unprofessional',
 'Delays',
 'Miscommunication',
 'Mistake',
 'Error-prone',
 'Unattended',
 'Unaddressed',
 'Oversight',
 'Blunder',
 'Poor Communication',
 'Unsolved',
 'Uncooperative',
 'Unhelpful',
 'Insufficient',
 'Lack of Accountability',
 'Confusion',
 'Hassle',
 'Mismanagement',
 'Inaccuracy',
 'Inadequate',
 'Unreliable',
 'Service Failure',
 'Customer Service Issue',
 'Quality Issue',
 'Technical Issue',
 'Billing Issue',
 'Product Issue',
 'Shipping Issue',
 'Delivery Issue',
 'Warranty Issue',
 'Return Issue',
 'Refund Issue',
 'Exchange Issue',
 'Contract Issue',
 'Policy Issue',
 'Procedure Issue',
 'Unsatisfactory Resolution',
 'Complaint Handling',
 'Customer Complaint',
 'Dissatisfied Customer',
 'Complaint Process',
 'Complaint Resolution',
 'Customer Experience',
 'Feedback',
 'Unsatisfied Customer',
 'Unhappy Customer',
 'Complaint Escalation',
 'Customer Dissatisfaction',
 'Customer Displeasure',
 'Unresolved Complaint',
 'Service Complaint',
 'Product Complaint',
 'Delivery Complaint',
 'Billing Complaint',
 'Warranty Complaint',
 'Return Complaint',
 'Refund Complaint',
 'Exchange Complaint',
 'Contract Complaint',
 'Policy Complaint',
 'Procedure Complaint',
 'Billing Dispute',
 'Product Defect',
 'Service Deficiency',
 'Shipping Delay',
 'Delivery Error',
 'Warranty Denial',
 'Return Rejection',
 'Refund Delay',
 'Exchange Denial',
 'Contract Breach',
 'Policy Violation',
 'Procedure Error',
 'Customer Support Issue',
 'Billing Error',
 'Product Misrepresentation',
 'Service Misconduct',
 'Shipping Damage',
 'Delivery Loss',
 'Warranty Dispute',
 'Return Difficulties',
 'Refund Denial',
 'Exchange Difficulty',
 'Contract Dispute',
 'Policy Disagreement',
 'Procedure Inefficiency',
 'Unfair Billing',
 'Product Non-conformity',
 'Service Non-compliance',
 'Shipping Inaccuracy',
 'Delivery Non-performance',
 'Warranty Non-fulfillment',
 'Return Inconvenience',
 'Refund Disagreement',
 'Exchange Displeasure',
 'Contract Non-adherence',
 'Policy Non-compliance',
 'Procedure Non-conformity',
 'Billing Injustice',
 'Product Complaints',
 'Service Complaints',
 'Shipping Complaints',
 'Delivery Complaints',
 'Billing Complaints',
 'Warranty Complaints',
 'Return Complaints',
 'Refund Complaints',
 'Exchange Complaints',
 'Contract Complaints',
 'Policy Complaints',
 'Procedure Complaints',
 'Unresolved Billing Issue',
 'Unresolved Product Issue',
 'Unresolved Service Issue',
 'Unresolved Shipping Issue',
 'Unresolved Delivery Issue',
 'Unresolved Warranty Issue',
 'Unresolved Return Issue',
 'Unresolved Refund Issue',
 'Unresolved Exchange Issue',
 'Unresolved Contract Issue',
 'Unresolved Policy Issue',
 'Unresolved Procedure Issue',
 'Unresolved Customer Service Issue',
 'Customer Service Complaints',
 'Customer Service Dissatisfaction',
 'Customer Service Displeasure',
 'Customer Service Unhappiness',
 'Customer Service Frustration',
 'Customer Service Unreliability',
 'Customer Service Inefficiency',
 'Customer Service Unprofessionalism',
 'Customer Service Delays',
 'Customer Service Miscommunication',
 'Customer Service Mistakes',
 'Customer Service Inadequacy',
 'Customer Service Confusion',
 'Customer Service Hassle',
 'Customer Service Mismanagement',
 'Customer Service Inaccuracy',
 'Customer Service Lack of Accountability',
 'Customer Service Oversight',
 'Customer Service Blunders',
 'Customer Service Unattended Issues',
 'Customer Service Unaddressed Concerns',
 'Customer Service Uncooperativeness',
 'Customer Service Unhelpfulness',
 'Customer Service Insufficiency',
 'Customer Service Lack of Communication',
 'Customer Service Apology',
 'Customer Service Regrettable Situation',
 'Customer Service Unsatisfactory Resolution',
 'Customer Service Handling Complaints',
 'Customer Service Complaint Process',
 'Customer Service Complaint Resolution',
 'Customer Service Unsatisfied Resolution',
 'Customer Service Dissatisfaction Resolution',
 'Customer Service Unhappy Resolution',
 'Customer Service Unresolved Complaint',
 'Customer Service Unsatisfied Customer',
 'Customer Service Unhappy Customer',
 'Customer Service Complaint Escalation',
 'Customer Service Dissatisfied Customer',
 'Customer Service Complaint Handling',
 'Customer Service Dissatisfaction Handling',
 'Customer Service Complaint Handling Process',
 'Customer Service Complaint Resolution Process',
 'Customer Service Resolution Time',
 'Customer Service Complaint Escalation Procedure',
 'Customer Service Unsatisfied Customer Resolution']

sales_cat_list = ['Inquiry',
 'Interest',
 'Product',
 'Service',
 'Pricing',
 'Quotation',
 'Quote',
 'Cost',
 'Price',
 'Estimate',
 'Proposal',
 'Offer',
 'Sales',
 'Purchase',
 'Buying',
 'Order',
 'Availability',
 'Stock',
 'Catalog',
 'Brochure',
 'Features',
 'Specifications',
 'Options',
 'Customization',
 'Configuration',
 'Compatibility',
 'Trial',
 'Demo',
 'Test',
 'Evaluation',
 'Sample',
 'Discount',
 'Promotion',
 'Deal',
 'Special Offer',
 'Package',
 'Bundle',
 'Financing',
 'Payment',
 'Installment',
 'Credit',
 'Financing Options',
 'Terms',
 'Conditions',
 'Warranty',
 'Guarantee',
 'Return Policy',
 'Refund Policy',
 'Exchange Policy',
 'Upgrade',
 'Renewal',
 'Subscription',
 'Membership',
 'Licensing',
 'Agreement',
 'Contract',
 'Negotiation',
 'Closing',
 'Follow-up',
 'Lead',
 'Prospect',
 'Client',
 'Customer',
 'Potential Customer',
 'Target',
 'Audience',
 'Market',
 'Segment',
 'Industry',
 'Niche',
 'Audience',
 'Solution',
 'Problem-solving',
 'Benefit',
 'Advantage',
 'Value',
 'ROI (Return on Investment)',
 'TCO (Total Cost of Ownership)',
 'Savings',
 'Efficiency',
 'Performance',
 'Quality',
 'Reliability',
 'Durability',
 'Innovation',
 'Technology',
 'Features',
 'Functionality',
 'User-Friendly',
 'Ease of Use',
 'Convenience',
 'Customization',
 'Configuration',
 'Integration',
 'Compatibility',
 'Scalability',
 'Flexibility',
 'Adaptability',
 'Versatility',
 'User Experience (UX)',
 'Design',
 'Aesthetics',
 'Brand',
 'Brand Image',
 'Brand Reputation',
 'Trust',
 'Credibility',
 'Authenticity',
 'Recognition',
 'Authority',
 'Social Proof',
 'Testimonials',
 'Reviews',
 'References',
 'Case Studies',
 'Success Stories',
 'Partnerships',
 'Collaboration',
 'Affiliation',
 'Certification',
 'Awards',
 'Recognition',
 'Achievements',
 'Milestones',
 'Experience',
 'Expertise',
 'Knowledge',
 'Skills',
 'Training',
 'Education',
 'Certifications',
 'Qualifications',
 'Credentials',
 'Team',
 'Leadership',
 'Culture',
 'Values',
 'Mission',
 'Vision',
 'Goals',
 'Objectives',
 'Strategy',
 'Planning',
 'Execution',
 'Implementation',
 'Support',
 'Assistance',
 'Service Level Agreement (SLA)',
 'Maintenance',
 'Upkeep',
 'Technical Support',
 'Helpdesk',
 'Customer Support',
 'After-Sales Service',
 'Communication',
 'Response Time',
 'Engagement',
 'Relationship',
 'Partnership',
 'Collaboration',
 'Consultation',
 'Advisory',
 'Consultative Selling',
 'Needs Analysis',
 'Solution-oriented',
 'Problem-solving',
 'Consultation',
 'Advisory',
 'Consultative Selling',
 'Needs Analysis',
 'Solution-oriented',
 'Problem-solving',
 'Custom Solution',
 'Personalization',
 'Tailored',
 'Made-to-order',
 'Bespoke',
 'Unique',
 'Differentiation',
 'Competitive Advantage',
 'Market Differentiation',
 'Positioning',
 'Branding',
 'Marketing',
 'Promotion',
 'Advertising',
 'Campaign',
 'Lead Generation',
 'Prospecting',
 'Cold Calling',
 'Warm Leads',
 'Sales Funnel',
 'Conversion',
 'Closing',
 'Objections',
 'Objection Handling',
 'Trial Close',
 'Consultative Close',
 'Direct Close']

collaboration_cat_list = ['Collaboration',
 'Partnership',
 'Alliance',
 'Cooperation',
 'Joint Venture',
 'Synergy',
 'Networking',
 'Team-Up',
 'Joint Effort',
 'Mutual',
 'Venture',
 'Combined Effort',
 'Strategic Alliance',
 'Business Partnership',
 'Co-creation',
 'Co-development',
 'Co-innovation',
 'Co-marketing',
 'Co-selling',
 'Co-branding',
 'Co-production',
 'Co-distribution',
 'Co-investment',
 'Co-financing',
 'Co-ownership',
 'Co-manufacturing',
 'Co-presentation',
 'Co-exhibition',
 'Co-promotion',
 'Co-sponsorship',
 'Co-event',
 'Co-creation',
 'Shared Vision',
 'Shared Goals',
 'Shared Objectives',
 'Common Interest',
 'Collaborative Project',
 'Collaborative Initiative',
 'Collaborative Program',
 'Collaborative Research',
 'Collaborative Development',
 'Collaborative Design',
 'Collaborative Innovation',
 'Collaborative Marketing',
 'Collaborative Selling',
 'Collaborative Branding',
 'Collaborative Production',
 'Collaborative Distribution',
 'Collaborative Investment',
 'Collaborative Financing',
 'Collaborative Ownership',
 'Collaborative Management',
 'Collaborative Planning',
 'Collaborative Execution',
 'Collaborative Implementation',
 'Collaborative Strategy',
 'Collaborative Tactics',
 'Collaborative Operations',
 'Collaborative Logistics',
 'Collaborative Support',
 'Collaborative Services',
 'Collaborative Solutions',
 'Collaborative Products',
 'Collaborative Technologies',
 'Collaborative Systems',
 'Collaborative Processes',
 'Collaborative Workflow',
 'Collaborative Communication',
 'Collaborative Relationship',
 'Collaborative Engagement',
 'Collaborative Interaction',
 'Collaborative Exchange',
 'Collaborative Connection',
 'Collaborative Networking',
 'Collaborative Teamwork',
 'Collaborative Coordination',
 'Collaborative Integration',
 'Collaborative Alignment',
 'Collaborative Adaptation',
 'Collaborative Flexibility',
 'Collaborative Innovation',
 'Collaborative Creativity',
 'Collaborative Problem-solving',
 'Collaborative Decision-making',
 'Collaborative Strategy',
 'Collaborative Planning',
 'Collaborative Execution',
 'Collaborative Implementation',
 'Collaborative Evaluation',
 'Collaborative Impact',
 'Collaborative Success',
 'Collaborative Achievements',
 'Collaborative Milestones',
 'Collaborative Benefits',
 'Collaborative Value',
 'Collaborative Growth',
 'Collaborative Development',
 'Collaborative Progress',
 'Collaborative Expansion',
 'Collaborative Market Reach',
 'Collaborative Customer Base',
 'Collaborative Brand Equity',
 'Collaborative Revenue',
 'Collaborative Profits',
 'Collaborative ROI (Return on Investment)',
 'Collaborative Recognition',
 'Collaborative Reputation',
 'Collaborative Authority',
 'Collaborative Influence',
 'Collaborative Impact',
 'Collaborative Contribution',
 'Collaborative Community',
 'Collaborative Social Responsibility',
 'Collaborative Sustainability',
 'Collaborative Environmental Impact',
 'Collaborative Ethical Practices',
 'Collaborative Diversity',
 'Collaborative Inclusion',
 'Collaborative Corporate Values',
 'Collaborative Social Impact',
 'Collaborative Innovation',
 'Collaborative Creativity',
 'Collaborative Problem-solving',
 'Collaborative Decision-making',
 'Collaborative Strategy',
 'Collaborative Planning',
 'Collaborative Execution',
 'Collaborative Implementation',
 'Collaborative Evaluation',
 'Collaborative Impact',
 'Collaborative Success',
 'Collaborative Achievements',
 'Collaborative Milestones',
 'Collaborative Benefits',
 'Collaborative Value',
 'Collaborative Growth',
 'Collaborative Development',
 'Collaborative Progress',
 'Collaborative Expansion',
 'Collaborative Market Reach',
 'Collaborative Customer Base',
 'Collaborative Brand Equity',
 'Collaborative Revenue',
 'Collaborative Profits',
 'Collaborative ROI (Return on Investment)',
 'Collaborative Recognition',
 'Collaborative Reputation',
 'Collaborative Authority',
 'Collaborative Influence',
 'Collaborative Impact',
 'Collaborative Contribution',
 'Collaborative Community',
 'Collaborative Social Responsibility',
 'Collaborative Sustainability',
 'Collaborative Environmental Impact',
 'Collaborative Ethical Practices',
 'Collaborative Diversity',
 'Collaborative Inclusion',
 'Collaborative Corporate Values',
 'Collaborative Social Impact',
 'Collaborative Outreach',
 'Collaborative Awareness',
 'Collaborative Engagement',
 'Collaborative Interaction',
 'Collaborative Communication',
 'Collaborative Exposure',
 'Collaborative Promotion',
 'Collaborative Campaign',
 'Collaborative Event',
 'Collaborative Initiative',
 'Collaborative Sponsorship',
 'Collaborative Endorsement',
 'Collaborative Participation',
 'Collaborative Involvement',
 'Collaborative Contribution',
 'Collaborative Support',
 'Collaborative Cooperation',
 'Collaborative Connection',
 'Collaborative Networking',
 'Collaborative Partnership',
 'Collaborative Collaboration',
 'Collaborative Synergy',
 'Collaborative Unity',
 'Collaborative Trust',
 'Collaborative Relationship',
 'Collaborative Agreement',
 'Collaborative Contract',
 'Collaborative Understanding',
 'Collaborative Commitment',
 'Collaborative Flexibility',
 'Collaborative Adaptability',
 'Collaborative Alignment',
 'Collaborative Integration',
 'Collaborative Growth',
 'Collaborative Potential',
 'Collaborative Possibilities',
 'Collaborative Prospects',
 'Collaborative Future',
 'Collaborative Exploration']

internel_cat_list = ['Internal',
 'Communication',
 'Announcement',
 'Update',
 'Memo',
 'Notice',
 'Information',
 'Directive',
 'Guidance',
 'Policy',
 'Procedure',
 'Protocol',
 'Instruction',
 'Reminder',
 'Clarification',
 'Confirmation',
 'Acknowledgment',
 'Request',
 'Inquiry',
 'Feedback',
 'Response',
 'Coordination',
 'Collaboration',
 'Team',
 'Department',
 'Division',
 'Unit',
 'Office',
 'Branch',
 'Site',
 'Location',
 'Facility',
 'Center',
 'Headquarters',
 'Leadership',
 'Management',
 'Supervisor',
 'Manager',
 'Executive',
 'Director',
 'Vice President',
 'President',
 'CEO (Chief Executive Officer)',
 'CFO (Chief Financial Officer)',
 'CTO (Chief Technology Officer)',
 'COO (Chief Operating Officer)',
 'CMO (Chief Marketing Officer)',
 'CHRO (Chief Human Resources Officer)',
 'CIO (Chief Information Officer)',
 'CISO (Chief Information Security Officer)',
 'Teamwork',
 'Collaboration',
 'Cooperation',
 'Coordination',
 'Synergy',
 'Alignment',
 'Integration',
 'Unity',
 'Harmony',
 'Consistency',
 'Consensus',
 'Decision',
 'Agreement',
 'Approval',
 'Ratification',
 'Authorization',
 'Endorsement',
 'Validation',
 'Confirmation',
 'Assent',
 'Consent',
 'Compliance',
 'Adherence',
 'Conformity',
 'Uniformity',
 'Standardization',
 'Guidelines',
 'Best Practices',
 'Benchmark',
 'Standard',
 'Norms',
 'Protocols',
 'Policies',
 'Procedures',
 'Instructions',
 'Rules',
 'Regulations',
 'Compliance',
 'Conformance',
 'Adaptation',
 'Adjustment',
 'Modification',
 'Change',
 'Transformation',
 'Innovation',
 'Improvement',
 'Development',
 'Progress',
 'Growth',
 'Achievement',
 'Milestone',
 'Success',
 'Performance',
 'Results',
 'Outcomes',
 'Metrics',
 'Data',
 'Analytics',
 'Reporting',
 'Monitoring',
 'Evaluation',
 'Assessment',
 'Measurement',
 'KPIs (Key Performance Indicators)',
 'Metrics',
 'Objectives',
 'Goals',
 'Targets',
 'Priorities',
 'Focus',
 'Strategy',
 'Planning',
 'Execution',
 'Implementation',
 'Project',
 'Initiative',
 'Task',
 'Activity',
 'Assignment',
 'Responsibility',
 'Accountability',
 'Ownership',
 'Leadership',
 'Management',
 'Supervision',
 'Direction',
 'Authority',
 'Delegation',
 'Empowerment',
 'Decision-making',
 'Problem-solving',
 'Resolution',
 'Conflict',
 'Issue',
 'Challenge',
 'Opportunity',
 'Risk',
 'Mitigation',
 'Contingency',
 'Crisis',
 'Emergency',
 'Response',
 'Recovery',
 'Business Continuity',
 'Disaster',
 'Incident',
 'Incident Management',
 'Communication Plan',
 'Crisis Communication',
 'Employee',
 'Staff',
 'Workforce',
 'Team',
 'Colleague',
 'Coworker',
 'Peer',
 'Subordinate',
 'Supervisor',
 'Manager',
 'Executive',
 'Leadership',
 'C-Suite',
 'Employee Engagement',
 'Morale',
 'Well-being',
 'Wellness',
 'Health',
 'Safety',
 'Security',
 'Training',
 'Development',
 'Learning',
 'Skills',
 'Knowledge',
 'Competency',
 'Talent',
 'Performance',
 'Appraisal',
 'Recognition',
 'Reward',
 'Compensation',
 'Benefits',
 'Incentive',
 'Motivation',
 'Employee Relations',
 'Employee Satisfaction',
 'Employee Experience',
 'Workplace Culture',
 'Diversity']

legal_cat_list = ['Legal',
 'Matters',
 'Law',
 'Legalities',
 'Compliance',
 'Regulations',
 'Rules',
 'Policies',
 'Procedures',
 'Governance',
 'Statutes',
 'Acts',
 'Legislation',
 'Guidelines',
 'Requirements',
 'Obligations',
 'Duties',
 'Responsibilities',
 'Rights',
 'Entitlements',
 'Privileges',
 'Immunities',
 'Liabilities',
 'Indemnities',
 'Disputes',
 'Litigation',
 'Lawsuit',
 'Legal Action',
 'Legal Proceedings',
 'Legal Counsel',
 'Attorney',
 'Lawyer',
 'Legal Advisor',
 'Legal Representative',
 'Legal Assistance',
 'Legal Support',
 'Legal Advice',
 'Legal Opinion',
 'Contract',
 'Agreement',
 'Terms',
 'Conditions',
 'Clause',
 'Provision',
 'Covenant',
 'Undertaking',
 'Commitment',
 'Warranty',
 'Guarantee',
 'Binding',
 'Enforceable',
 'Consent',
 'Authorization',
 'Approval',
 'Ratification',
 'Signature',
 'Execution',
 'Notarization',
 'Witness',
 'Counterparty',
 'Party',
 'Parties',
 'Performance',
 'Breach',
 'Termination',
 'Rescission',
 'Amendment',
 'Modification',
 'Waiver',
 'Release',
 'Confidentiality',
 'Non-Disclosure',
 'Privacy',
 'Data Protection',
 'Intellectual Property',
 'Copyright',
 'Trademark',
 'Patent',
 'Trade Secret',
 'Licensing',
 'Royalties',
 'Infringement',
 'Violation',
 'Cease and Desist',
 'Notice',
 'Warning',
 'Injunction',
 'Restraining Order',
 'Court Order',
 'Settlement',
 'Arbitration',
 'Mediation',
 'Dispute Resolution',
 'Legal Document',
 'Legal Instrument',
 'Legal Notice',
 'Legal Form',
 'Legal Requirement',
 'Legal Compliance',
 'Legal Review',
 'Legal Proceedings',
 'Legal Consequences',
 'Legal Implications',
 'Legal Responsibility',
 'Legal Authority',
 'Legal Standards',
 'Legal Precedent',
 'Legal Advice',
 'Legal Assistance',
 'Legal Support',
 'Legal Documentation',
 'Legal Drafting',
 'Legal Language',
 'Legal Interpretation',
 'Legal Code',
 'Legal System',
 'Legal Framework',
 'Legal Expertise',
 'Legal Understanding',
 'Legal Consideration',
 'Legal Counsel',
 'Legal Representation',
 'Legal Consultation',
 'Legal Opinion',
 'Legal Risk',
 'Legal Compliance',
 'Legal Liability',
 'Legal Consequences',
 'Legal Obligations',
 'Legal Safeguards',
 'Legal Protections',
 'Legal Rights',
 'Legal Privileges',
 'Legal Immunities',
 'Legal Challenges',
 'Legal Requirements',
 'Legal Compliance',
 'Legal Interpretation',
 'Legal Compliance',
 'Legal Obligations',
 'Legal Safeguards',
 'Legal Protections',
 'Legal Rights',
 'Legal Privileges',
 'Legal Immunities',
 'Legal Challenges',
 'Legal Aspects',
 'Legal Implications',
 'Legal Consequences',
 'Legal Procedures',
 'Legal Formalities',
 'Legal Representation',
 'Legal Counsel',
 'Legal Assistance',
 'Legal Support',
 'Legal Framework',
 'Legal Structure',
 'Legal Entities',
 'Legal Person',
 'Legal Entity',
 'Legal Entity',
 'Legal Standing',
 'Legal Status',
 'Legal Personality',
 'Legal Formation',
 'Legal Recognition',
 'Legal Capacity',
 'Legal Rights',
 'Legal Liabilities',
 'Legal Duties',
 'Legal Responsibilities',
 'Legal Obligations',
 'Legal Authority',
 'Legal Jurisdiction',
 'Legal Venue',
 'Legal Proceedings',
 'Legal Process',
 'Legal System',
 'Legal Institution',
 'Legal Expertise',
 'Legal Professional',
 'Legal Practice',
 'Legal Code',
 'Legal Language',
 'Legal Drafting',
 'Legal Interpretation',
 'Legal Analysis',
 'Legal Argument',
 'Legal Opinion',
 'Legal Decision',
 'Legal Precedent',
 'Legal Reference',
 'Legal Citation',
 'Legal Research',
 'Legal Case',
 'Legal Brief',
 'Legal Memo',
 'Legal Document',
 'Legal Instrument']

marketing_cat_list = ['Marketing',
 'Promotions',
 'Advertising',
 'Campaign',
 'Strategy',
 'Plan',
 'Promotion',
 'Advertisement',
 'Sale',
 'Offer',
 'Discount',
 'Deal',
 'Special',
 'Savings',
 'Limited Time',
 'Exclusive',
 'Coupon',
 'Voucher',
 'Code',
 'Flash Sale',
 'Clearance',
 'BOGO (Buy One Get One)',
 'Free',
 'Gift',
 'Giveaway',
 'Contest',
 'Sweepstakes',
 'Prize',
 'Rewards',
 'Loyalty',
 'Points',
 'Membership',
 'VIP',
 'Early Access',
 'Preview',
 'Sneak Peek',
 'New Arrival',
 'Latest',
 'Trendy',
 'Hot',
 'Popular',
 'Bestseller',
 'Featured',
 'Top Picks',
 "Editor's Choice",
 'Recommended',
 'Must-Have',
 'Best Value',
 'Quality',
 'Premium',
 'Luxury',
 'Exclusive Collection',
 'Limited Edition',
 'Custom',
 'Personalized',
 'Tailored',
 'Bespoke',
 'Handcrafted',
 'Artisanal',
 'Made-to-Order',
 'Unique',
 'Original',
 'Authentic',
 'Innovative',
 'Trendsetting',
 'Cutting-edge',
 'Modern',
 'Classic',
 'Timeless',
 'Elegant',
 'Stylish',
 'Fashionable',
 'Chic',
 'Sophisticated',
 'Glamorous',
 'Casual',
 'Comfortable',
 'Functional',
 'Practical',
 'Versatile',
 'Affordable',
 'Budget-Friendly',
 'Value for Money',
 'Cost-Effective',
 'Savings',
 'Economical',
 'Price',
 'Cost',
 'Budget',
 'Financial',
 'Investment',
 'Return on Investment (ROI)',
 'Profit',
 'Revenue',
 'Sales',
 'Conversion',
 'Customer Acquisition',
 'Customer Retention',
 'Engagement',
 'Interaction',
 'Communication',
 'Connection',
 'Relationship',
 'Trust',
 'Credibility',
 'Authenticity',
 'Transparency',
 'Honesty',
 'Integrity',
 'Reputation',
 'Brand',
 'Branding',
 'Brand Identity',
 'Brand Image',
 'Brand Recognition',
 'Brand Loyalty',
 'Brand Ambassador',
 'Influencer',
 'Social Media',
 'Online Presence',
 'Website',
 'E-commerce',
 'Online Store',
 'Mobile App',
 'User Experience (UX)',
 'Interface',
 'Navigation',
 'Accessibility',
 'Responsive Design',
 'Mobile-Friendly',
 'SEO (Search Engine Optimization)',
 'SEM (Search Engine Marketing)',
 'PPC (Pay-Per-Click)',
 'Adwords',
 'Social Media Marketing',
 'Content Marketing',
 'Email Marketing',
 'Influencer Marketing',
 'Affiliate Marketing',
 'Video Marketing',
 'Podcast',
 'Webinar',
 'Virtual Event',
 'Experiential Marketing',
 'Guerrilla Marketing',
 'Viral Marketing',
 'Interactive',
 'Multimedia',
 'Infographic',
 'Graphic Design',
 'Photography',
 'Videography',
 'Animation',
 'Illustration',
 'Typography',
 'Color Palette',
 'Visual Elements',
 'Aesthetics',
 'Creativity',
 'Innovation',
 'Trends',
 'Insights',
 'Analytics',
 'Data-driven',
 'Metrics',
 'Measurement',
 'ROI (Return on Investment)',
 'KPIs (Key Performance Indicators)',
 'Customer Journey',
 'User Persona',
 'Target Audience',
 'Market Segment',
 'Demographics',
 'Psychographics',
 'Behavior',
 'Preferences',
 'Trends',
 'Forecast',
 'Analysis',
 'Research',
 'Survey',
 'Focus Group',
 'Feedback',
 'Testimonials',
 'Reviews',
 'Ratings',
 'Recommendations',
 'Endorsements',
 'Testimonials',
 'Reviews',
 'Ratings',
 'Recommendations',
 'Endorsements',
 'Customer Testimonials',
 'Case Studies',
 'Success Stories',
 'Behind the Scenes',
 'Making Of',
 'Insider']

events_cat_list = ['Event',
 'Invitation',
 'Participate',
 'Collaborate',
 'Join',
 'Attend',
 'RSVP',
 'Save the Date',
 'Calendar',
 'Schedule',
 'Agenda',
 'Program',
 'Itinerary',
 'Venue',
 'Location',
 'Date',
 'Time',
 'Day',
 'Occasion',
 'Celebration',
 'Ceremony',
 'Festivity',
 'Gathering',
 'Assembly',
 'Meetup',
 'Conclave',
 'Summit',
 'Conference',
 'Forum',
 'Seminar',
 'Workshop',
 'Training',
 'Session',
 'Panel',
 'Roundtable',
 'Discussion',
 'Keynote',
 'Speaker',
 'Presenter',
 'Expert',
 'Facilitator',
 'Moderator',
 'Host',
 'Organizers',
 'Planning',
 'Coordination',
 'Logistics',
 'Setup',
 'Decor',
 'Catering',
 'Refreshments',
 'Networking',
 'Connections',
 'Relationship-building',
 'Interaction',
 'Engagement',
 'Collaboration',
 'Partnership',
 'Sponsorship',
 'Support',
 'Involvement',
 'Contribution',
 'Participation',
 'Contribution',
 'Involvement',
 'Engagement',
 'Activation',
 'Interaction',
 'Connection',
 'Networking',
 'Relationship-building',
 'Collaboration',
 'Partnership',
 'Sponsorship',
 'Support',
 'Alignment',
 'Synergy',
 'Cooperation',
 'Unity',
 'Joint Effort',
 'Coordinated',
 'Cohesive',
 'Unified',
 'Teamwork',
 'Group',
 'Community',
 'Audience',
 'Guests',
 'Participants',
 'Attendees',
 'Delegates',
 'Representatives',
 'Ambassadors',
 'Members',
 'Supporters',
 'Advocates',
 'Promoters',
 'Evangelists',
 'Allies',
 'Champions',
 'Enthusiasts',
 'Fans',
 'Followers',
 'Supporters',
 'Backers',
 'Sponsors',
 'Partners',
 'Collaborators',
 'Affiliates',
 'Associates',
 'Allies',
 'Friends',
 'Colleagues',
 'Peers',
 'Acquaintances',
 'Network',
 'Connection',
 'Relationship',
 'Friendship',
 'Acquaintance',
 'Communication',
 'Interaction',
 'Collaboration',
 'Partnership',
 'Alliance',
 'Relationship-building',
 'Engagement',
 'Networking',
 'Connection',
 'Interaction',
 'Collaboration',
 'Partnership',
 'Alliance',
 'Relationship-building',
 'Engagement',
 'Networking',
 'Connection',
 'Relationship',
 'Partnership',
 'Interaction',
 'Collaboration',
 'Networking',
 'Engagement',
 'Involvement',
 'Participation',
 'Contribution',
 'Support',
 'Sponsorship',
 'Alignment',
 'Synergy',
 'Cooperation',
 'Unity',
 'Joint Effort',
 'Coordination',
 'Cohesiveness',
 'Harmony',
 'Connection',
 'Interaction',
 'Relationship-building',
 'Engagement',
 'Networking',
 'Collaboration',
 'Partnership',
 'Alliance',
 'Relationship-building',
 'Engagement',
 'Networking',
 'Connection',
 'Interaction',
 'Collaboration',
 'Partnership',
 'Alliance',
 'Relationship-building',
 'Engagement',
 'Networking',
 'Connection',
 'Relationship',
 'Partnership',
 'Interaction',
 'Collaboration',
 'Networking',
 'Engagement',
 'Involvement',
 'Participation',
 'Contribution',
 'Support',
 'Sponsorship',
 'Alignment',
 'Synergy',
 'Cooperation',
 'Unity',
 'Joint Effort',
 'Coordination',
 'Cohesiveness',
 'Harmony',
 'Connection',
 'Interaction',
 'Relationship-building',
 'Engagement']


categories_key_words_dict = {
    'General Inquiries': general_cat_list,
    'Technical Support': Technical_cat_list,
    'Customer Feedback': feedback_cat_list,
    'Complaints': complaints_cat_list,
    'Sales Inquiries': sales_cat_list,
    'Collaboration Opportunities': collaboration_cat_list,
    'Internal Communication': internel_cat_list,
    'Legal Matters': legal_cat_list,
    'Marketing and Promotions': marketing_cat_list,
    'Event Invitations': events_cat_list
}